language: node_js
node_js:
  - 14
env:
  - CI=yes
cache: npm
notifications:
  email: false
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: build
  fqdn: downcloud.ruud.ninja
  on:
    branch: master
