language: node_js
node_js:
  - 8
env:
  - CI=yes
cache:
  directories:
  - "$HOME/.npm"
notifications:
  email: false
install:
  - npm install
script:
  - npm run build
  - npm test
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: build
  fqdn: downcloud.ruud.ninja
  on:
    branch: master
