language: node_js
node_js:
  - 6
env:
  - CI=yes
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run build
  - npm test
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: build
  fqdn: downcloud.ruud.ninja
  on:
    branch: master