language: node_js
node_js:
  - 14
notifications:
  email: false
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  local_dir: build
  fqdn: downcloud.ruud.ninja
  on:
    tags: true
